### ISSUE TITLE
Your usage example returns NaN

### ISSUE THREAD

**Issue by krabbypattified** [Tom-Alexander/regression-js#67]
This

	const regression = require('regression')
	const result = regression.linear([0, 1], [32, 67], [12, 79]);
	const gradient = result.equation[0];
	const yIntercept = result.equation[1];
	console.log(gradient);
	console.log(yIntercept);
	console.log(result.predict(5));

returns

    NaN
    NaN
    [ 5, NaN ]

**Comment by KirillGrishin** [comment]
Same here, even the example in readme returns NaN. What is wrong? Is this even usable?

**Comment by mvberg** [comment]
there is a small discrepancy (typo) between github.io + npm docs vs [README.md](https://github.com/Tom-Alexander/regression-js/blob/master/README.md)

the `regression.*` methods expect an "array of arrays" as the first arg, so:

```js
const result = regression.linear([[0, 1], [32, 67], [12, 79]]);
```

and, yes, it's usable.

**Comment by Tom-Alexander** [comment]
Fixed in #72

**Comment by KevinJue** [comment]
@Tom-Alexander  i'm not sure of the fix. 

I use logarithmic function with data [ [ '1515068925', '2.72500' ], [ '1515068903', '2.72000' ] ]
and result is like that: 
```
{ points: 
   [ [ 1515068814, NaN ],
     [ 1515068797, NaN ],
     [ 1515068789, NaN ],
     [ 1515068783, NaN ],
     [ 1515068774, NaN ] ],
  predict: [Function: predict],
  equation: [ NaN, NaN ],
  string: 'y = NaN + NaN ln(x)',
  r2: NaN }
```

is it because of decimal value ? 
(Linear function work)

**Comment by KevinYuk** [comment]
Any update?

regression.polynomial still doesn't work. Return NaN.
